// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CompanyCode.ApiTemplate.Repository.SqlServer.Entities
{
    [Table("sys_log")]
    public partial class SysLog
    {
        [Key]
        public long Id { get; set; }
        [Column("log_thread")]
        [StringLength(256)]
        public string LogThread { get; set; }
        [Column("log_level")]
        [StringLength(50)]
        public string LogLevel { get; set; }
        [Column("log_logger")]
        public string LogLogger { get; set; }
        [Column("log_message")]
        public string LogMessage { get; set; }
        [Column("log_exception")]
        public string LogException { get; set; }
        [Column("log_source")]
        public string LogSource { get; set; }
        [Column("log_type")]
        public string LogType { get; set; }
        [Column("app_type")]
        [StringLength(256)]
        public string AppType { get; set; }
        [Column("device_name")]
        [StringLength(256)]
        public string DeviceName { get; set; }
        [Column("user_agent")]
        [StringLength(256)]
        public string UserAgent { get; set; }
        [Column("log_date", TypeName = "datetime")]
        public DateTime LogDate { get; set; }
        [Column("log_ip_address")]
        [StringLength(256)]
        public string LogIpAddress { get; set; }
        [Column("log_transaction_id")]
        public int? LogTransactionId { get; set; }
        [Column("action")]
        [StringLength(50)]
        public string Action { get; set; }
        [Column("controller")]
        [StringLength(50)]
        public string Controller { get; set; }
        [Column("url")]
        [StringLength(500)]
        public string Url { get; set; }
        [Column("logger")]
        [StringLength(250)]
        public string Logger { get; set; }
    }
}